version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - ./.var/mongo:/data/db

  api:
    container_name: api
    profiles:
      - manual
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          action: rebuild
    depends_on:
      - mongo
